# Generated by Django 4.2.2 on 2023-07-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot_app', '0012_profile_end_subscription_profile_is_subscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='последнее обновление')),
                ('prev_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments_app.order', verbose_name='предыдущий счёт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot_app.profile', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'счёт',
                'verbose_name_plural': 'счета',
            },
        ),
    ]
