# Generated by Django 4.2.2 on 2023-06-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0002_profile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, verbose_name='код')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, verbose_name='код')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot_app.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
    ]
