# Generated by Django 4.2.2 on 2023-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0003_country_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('title',), 'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('title',), 'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
    ]
