# Generated by Django 4.2.2 on 2023-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0004_alter_city_options_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, verbose_name='код')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'аэропорт',
                'verbose_name_plural': 'аэропорты',
            },
        ),
    ]
