# Generated by Django 4.2.2 on 2023-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0005_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('code', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, verbose_name='код')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'авиакомпания',
                'verbose_name_plural': 'авиакомпании',
            },
        ),
    ]
