# Generated by Django 4.2.2 on 2023-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0006_airline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('priority', 'title'), 'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('priority', 'title'), 'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
        migrations.AddField(
            model_name='city',
            name='priority',
            field=models.IntegerField(default=300, verbose_name='приоритет'),
        ),
        migrations.AddField(
            model_name='country',
            name='priority',
            field=models.IntegerField(default=300, verbose_name='приоритет'),
        ),
    ]
