# Generated by Django 4.2.2 on 2023-06-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0008_excursioncountry_rename_city_aviacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursioncity',
            options={'ordering': ('id',), 'verbose_name': 'страна экскурсии', 'verbose_name_plural': 'страны экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='excursioncountry',
            options={'ordering': ('id',), 'verbose_name': 'страна экскурсии', 'verbose_name_plural': 'страны экскурсии'},
        ),
        migrations.CreateModel(
            name='FlightSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateField(verbose_name='дата отправления')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='дата возвращения')),
                ('last_price', models.IntegerField(verbose_name='последняя цена')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_arrival_city', to='tgbot_app.aviacity', verbose_name='город прибытия')),
                ('depart_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_depart_city', to='tgbot_app.aviacity', verbose_name='город отправления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot_app.profile', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подписка на билет',
                'verbose_name_plural': 'подписки на билеты',
            },
        ),
    ]
