# Generated by Django 4.2.2 on 2023-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0009_alter_excursioncity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsubscription',
            name='is_direct',
            field=models.BooleanField(default=True, verbose_name='без пересадок'),
            preserve_default=False,
        ),
    ]
