# Generated by Django 4.2.2 on 2023-06-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advphoto',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
