# Generated by Django 4.2.2 on 2023-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0002_alter_advphoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='target',
            field=models.CharField(choices=[('paid', 'подписчики'), ('unpaid', 'не подписчики'), ('all', 'все')], default='unpaid', max_length=10, verbose_name='аудитория'),
        ),
    ]
